name: 'Setup Node.js Environment'
description: 'Setup Node.js with pnpm and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v5
      with:
        version: 10.12.4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24.14.1'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Generate Prisma Client
      shell: bash
      run: pnpm exec prisma generate
