# Codecov Configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        target: 95%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 5%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "**/*.config.{ts,js,mjs,cjs}"
  - "**/vitest.config.ts"
  - "**/next.config.ts"
  - "**/*.d.ts"
  - "**/types/**"
  - "**/prisma/**"
  - "**/setupTests.ts"
  - "**/auth.ts"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/*.{test,spec}.{ts,tsx,js,jsx}"
  - "**/scripts/**"
  - "**/__mocks__/**"
  - "**/test-utils/**"

flags:
  unittests:
    paths:
      - src/
    carryforward: true
