'use server';

import getActionState from '@/app/lib/utils/auth/get-action-state';
import { setUnknownError } from '@/app/lib/utils/auth/auth-utils';
import signupSchema from '@/app/lib/validation/signup-schema';
import { redirect } from 'next/navigation';
import { generateUsername } from 'unique-username-generator';
import { signIn } from '../../../../auth';
import type { FormState } from '../types/form-state';
import { prisma } from '../prisma';
import { Prisma } from '@prisma/client';
import { CustomPrismaAdapter } from '@/app/lib/prisma-adapter';

export const signupAction = async (_initialState: FormState, payload: FormData): Promise<FormState> => {
  const permittedFieldNames = [
    'email',
    'termsAndConditions',
    'username',
  ];
  const { formState, parsed } = getActionState(payload, permittedFieldNames, signupSchema);

  if (parsed.success) {
    const adapter = CustomPrismaAdapter(prisma);

    try {
      const { email } = formState.fields;

      formState.hasTimeout = false;

      await adapter.createUser!({
        id: '', // Will be generated by Prisma
        email: parsed.data.email,
        emailVerified: null,
        name: null,
        image: null,
        username: generateUsername('', 4)
      });

      // Redirect happens way below because next throws an error if you redirect inside a try/catch
      // The property redirectTo is responsible for the magic link callback URL
      await signIn('nodemailer', { email, redirect: false, redirectTo: '/' });
      formState.success = true;
    } catch (error: unknown) {
      formState.success = false;
      // Check for MongoDB timeout errors
      if (error instanceof Error && (
        error.message.includes('ETIMEOUT') ||
        error.message.includes('timeout') ||
        error.message.includes('timed out') ||
        ('code' in error && error.code === 'ETIMEOUT')
      )) {
        formState.hasTimeout = true;
        if (!formState.errors) {
          formState.errors = {};
        }
        formState.errors.general = ['Connection timed out. Please try again.'];
      } else if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
        const duplicateKeyError = error as Prisma.PrismaClientKnownRequestError;

        if (duplicateKeyError?.meta?.target === 'User_email_key') {
          if (!formState.errors) {
            formState.errors = {};
          }

          formState.errors.email = ['Account with this email already exists'];
        } else {
          setUnknownError(formState);
        }
      } else {
        setUnknownError(formState);
      }
    }
  }

  if (formState.success) {
    return redirect(encodeURI(`/success/signup?email=${formState.fields.email}`));
  }

  return formState;
};
