import { Geist, Geist_Mono } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';

import AuthToolbar from './components/auth/auth-toolbar';
import Header from './components/header/header';
import { Providers } from './components/providers';

import type { Metadata } from 'next';

import './globals.css';

// Server-side environment validation on startup
if (typeof window === 'undefined') {
  // Dynamic import to avoid bundling in client
  import('@/app/lib/config/env-validation').then(({ validateEnvironment }) => {
    validateEnvironment();
  });
}

// Client-side: Detect and warn about HTTPS/HTTP mismatch in development
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  if (window.location.protocol === 'https:' && window.location.hostname === 'localhost') {
    console.error(
      '🚨 HTTPS DETECTED: You are accessing localhost via HTTPS. ' +
        'This will cause authentication and API issues. ' +
        'Please use http://localhost:3000 instead.'
    );
  }
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <Header />
          <div className="flex flex-col font-sans justify-center min-h-screen pt-[80px] px-1.5 md:pt-[180px]">
            <AuthToolbar />
            <main>{children}</main>
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
