import { Geist, Geist_Mono } from 'next/font/google';

import { Separator } from '@radix-ui/react-separator';

import { Toaster } from '@/components/ui/sonner';

import AuthToolbar from './components/auth/auth-toolbar';
import Footer from './components/footer/footer';
import Header from './components/header/header';
import { Providers } from './components/providers';

import type { Metadata } from 'next';

import './globals.css';

// Server-side environment validation on startup
if (typeof window === 'undefined') {
  // Dynamic import to avoid bundling in client
  import('@/app/lib/config/env-validation').then(({ validateEnvironment }) => {
    validateEnvironment();
  });
}

// Client-side: Detect and warn about HTTPS/HTTP mismatch in development
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  if (window.location.protocol === 'https:' && window.location.hostname === 'localhost') {
    console.error(
      '🚨 HTTPS DETECTED: You are accessing localhost via HTTPS. ' +
        'This will cause authentication and API issues. ' +
        'Please use http://localhost:3000 instead.'
    );
  }
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: false,
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        suppressHydrationWarning
      >
        <Providers>
          <Header />
          <main className="font-sans md:pt-[152px] px-1.5 flex flex-col flex-1 border-4 border-zinc-900">
            <AuthToolbar />
            <Separator className="my-0 h-px bg-zinc-300" />
            {children}
          </main>
          <Footer />
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
