import { Dawning_of_a_New_Day } from 'next/font/google';
import { headers } from 'next/headers';
import { userAgentFromString } from 'next/server';

import { Separator } from '@radix-ui/react-separator';

import { Toaster } from '@/components/ui/sonner';

import AuthToolbar from './components/auth/auth-toolbar';
import Footer from './components/footer/footer';
import Header from './components/header/header';
import { Providers } from './components/providers';

import type { Metadata } from 'next';

import './globals.css';

// Server-side environment validation on startup
if (typeof window === 'undefined') {
  // Dynamic import to avoid bundling in client
  import('@/app/lib/config/env-validation').then(({ validateEnvironment }) => {
    validateEnvironment();
  });
}

// Client-side: Detect and warn about HTTPS/HTTP mismatch in development
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  if (window.location.protocol === 'https:' && window.location.hostname === 'localhost') {
    console.error(
      '🚨 HTTPS DETECTED: You are accessing localhost via HTTPS. ' +
        'This will cause authentication and API issues. ' +
        'Please use http://localhost:3000 instead.'
    );
  }
}

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const dawningOfANewDay = Dawning_of_a_New_Day({
  variable: '--font-dawning-of-a-new-day',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: false,
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userAgent = (await headers()).get('user-agent') || '';
  const { device } = userAgentFromString(userAgent);
  const isMobile = device?.type === 'mobile' || device?.type === 'tablet';

  return (
    <html lang="en">
      <body
        className={`${dawningOfANewDay.variable} antialiased flex flex-col min-h-screen overflow-x-hidden max-w-full`}
        suppressHydrationWarning
      >
        <Providers>
          <Header isMobile={isMobile} />
          <main className="font-sans px-1.5 flex flex-col flex-1 w-full max-w-full overflow-x-hidden">
            <AuthToolbar />
            <Separator className="my-0 h-px bg-zinc-300" />
            {children}
          </main>
          <Footer />
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
