import { PrismaClient } from '@prisma/client';

import type { TestUser } from './auth-helpers';

/**
 * E2E database URL — always uses the local Docker MongoDB container.
 * Never reads from process.env.DATABASE_URL to prevent accidentally
 * wiping a remote Atlas database during test seeding.
 */
const E2E_DATABASE_URL =
  process.env.E2E_DATABASE_URL || 'mongodb://localhost:27018/boudreaux-e2e?directConnection=true';

/**
 * Deterministic test users with stable ObjectIds. These IDs must match the
 * users referenced in storageState auth cookies generated by global-setup.
 */
const TEST_USERS: Record<string, TestUser> = {
  regular: {
    id: '65a1b2c3d4e5f6a7b8c9d0e1',
    email: 'testuser@example.com',
    name: 'Test User',
    username: 'testuser',
    role: 'user',
    firstName: 'Test',
    lastName: 'User',
    emailVerified: new Date(),
  },
  admin: {
    id: '65a1b2c3d4e5f6a7b8c9d0e2',
    email: 'admin@example.com',
    name: 'Admin User',
    username: 'adminuser',
    role: 'admin',
    firstName: 'Admin',
    lastName: 'User',
    emailVerified: new Date(),
  },
};

/**
 * Idempotent seed script for the E2E test database. Clears all collections
 * and creates deterministic test data.
 */
async function seedTestDatabase() {
  // Safety guard: refuse to run against a remote database
  if (E2E_DATABASE_URL.includes('mongodb+srv') || E2E_DATABASE_URL.includes('mongodb.net')) {
    throw new Error(
      `E2E seed script refusing to run against a remote database: ${E2E_DATABASE_URL}\n` +
        'Set E2E_DATABASE_URL to a local MongoDB instance (e.g. mongodb://localhost:27018/boudreaux-e2e)'
    );
  }

  const prisma = new PrismaClient({
    datasourceUrl: E2E_DATABASE_URL,
  });

  try {
    // Clear all collections in dependency-safe order
    await prisma.releaseTrack.deleteMany({});
    await prisma.trackArtist.deleteMany({});
    await prisma.artistFeaturedArtist.deleteMany({});
    await prisma.artistRelease.deleteMany({});
    await prisma.artistGroup.deleteMany({});
    await prisma.artistLabel.deleteMany({});
    await prisma.artistUrl.deleteMany({});
    await prisma.releaseUrl.deleteMany({});
    await prisma.notification.deleteMany({});
    await prisma.image.deleteMany({});
    await prisma.url.deleteMany({});
    await prisma.featuredArtist.deleteMany({});
    await prisma.track.deleteMany({});
    await prisma.release.deleteMany({});
    await prisma.artist.deleteMany({});
    await prisma.group.deleteMany({});
    await prisma.authenticator.deleteMany({});
    await prisma.session.deleteMany({});
    await prisma.account.deleteMany({});
    await prisma.verificationToken.deleteMany({});
    await prisma.user.deleteMany({});

    // Create test users
    const adminUser = await prisma.user.create({
      data: {
        id: TEST_USERS.admin.id,
        email: TEST_USERS.admin.email,
        name: TEST_USERS.admin.name,
        username: TEST_USERS.admin.username,
        role: TEST_USERS.admin.role,
        firstName: TEST_USERS.admin.firstName,
        lastName: TEST_USERS.admin.lastName,
        emailVerified: new Date(),
        termsAndConditions: true,
      },
    });

    await prisma.user.create({
      data: {
        id: TEST_USERS.regular.id,
        email: TEST_USERS.regular.email,
        name: TEST_USERS.regular.name,
        username: TEST_USERS.regular.username,
        role: TEST_USERS.regular.role,
        firstName: TEST_USERS.regular.firstName,
        lastName: TEST_USERS.regular.lastName,
        emailVerified: new Date(),
        termsAndConditions: true,
      },
    });

    // Create artists for multi-select testing
    await Promise.all([
      prisma.artist.create({
        data: {
          firstName: 'Test',
          surname: 'Artist One',
          slug: 'test-artist-one',
          displayName: 'Test Artist One',
          publishedOn: new Date(),
        },
      }),
      prisma.artist.create({
        data: {
          firstName: 'Test',
          surname: 'Artist Two',
          slug: 'test-artist-two',
          displayName: 'Test Artist Two',
          publishedOn: new Date(),
        },
      }),
      prisma.artist.create({
        data: {
          firstName: 'Test',
          surname: 'Artist Three',
          slug: 'test-artist-three',
          displayName: 'Test Artist Three',
          publishedOn: new Date(),
        },
      }),
    ]);

    // Create releases for multi-select testing
    await Promise.all([
      prisma.release.create({
        data: {
          title: 'Test Release Alpha',
          releasedOn: new Date('2024-01-15'),
          coverArt: 'https://picsum.photos/seed/release1/400/400',
        },
      }),
      prisma.release.create({
        data: {
          title: 'Test Release Beta',
          releasedOn: new Date('2024-06-15'),
          coverArt: 'https://picsum.photos/seed/release2/400/400',
        },
      }),
    ]);

    // Create tracks for listing/editing tests
    await Promise.all([
      prisma.track.create({
        data: {
          title: 'E2E Test Track One',
          duration: 180,
          audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
          position: 0,
          publishedOn: new Date(),
        },
      }),
      prisma.track.create({
        data: {
          title: 'E2E Test Track Two',
          duration: 240,
          audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
          position: 1,
          publishedOn: new Date(),
        },
      }),
      prisma.track.create({
        data: {
          title: 'E2E Track For Deletion',
          duration: 120,
          audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
          position: 2,
        },
      }),
    ]);

    // Create notification banners for carousel testing
    const now = new Date();
    const thirtyDaysLater = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    await Promise.all([
      prisma.notification.create({
        data: {
          message: 'E2E Test Banner One',
          secondaryMessage: 'First test notification',
          isActive: true,
          isOverlayed: false,
          backgroundColor: '#16213e',
          sortOrder: 1,
          displayFrom: now,
          displayUntil: thirtyDaysLater,
          publishedAt: now,
          addedBy: { connect: { id: adminUser.id } },
        },
      }),
      prisma.notification.create({
        data: {
          message: 'E2E Test Banner Two',
          secondaryMessage: 'Second test notification',
          isActive: true,
          isOverlayed: false,
          backgroundColor: '#533483',
          sortOrder: 2,
          displayFrom: now,
          displayUntil: thirtyDaysLater,
          publishedAt: now,
          addedBy: { connect: { id: adminUser.id } },
        },
      }),
      prisma.notification.create({
        data: {
          message: 'E2E Test Banner Three',
          secondaryMessage: 'Third test notification',
          isActive: true,
          isOverlayed: false,
          backgroundColor: '#e94560',
          sortOrder: 3,
          displayFrom: now,
          displayUntil: thirtyDaysLater,
          publishedAt: now,
          addedBy: { connect: { id: adminUser.id } },
        },
      }),
    ]);

    console.info('E2E test database seeded successfully.');
  } finally {
    await prisma.$disconnect();
  }
}

export { seedTestDatabase, TEST_USERS };
