import { PrismaClient } from '@prisma/client';

import type { TestUser } from './auth-helpers';

/**
 * E2E database URL — always uses the local Docker MongoDB container.
 * Never reads from process.env.DATABASE_URL to prevent accidentally
 * wiping a remote Atlas database during test seeding.
 */
const E2E_DATABASE_URL =
  process.env.E2E_DATABASE_URL || 'mongodb://localhost:27018/boudreaux-e2e?replicaSet=rs0';

/**
 * Deterministic test users with stable ObjectIds. These IDs must match the
 * users referenced in storageState auth cookies generated by global-setup.
 */
const TEST_USERS: Record<string, TestUser> = {
  regular: {
    id: '65a1b2c3d4e5f6a7b8c9d0e1',
    email: 'testuser@example.com',
    name: 'Test User',
    username: 'testuser',
    role: 'user',
    firstName: 'Test',
    lastName: 'User',
    emailVerified: new Date(),
  },
  admin: {
    id: '65a1b2c3d4e5f6a7b8c9d0e2',
    email: 'admin@example.com',
    name: 'Admin User',
    username: 'adminuser',
    role: 'admin',
    firstName: 'Admin',
    lastName: 'User',
    emailVerified: new Date(),
  },
};

/**
 * Wait for the MongoDB replica set to be ready. The Docker healthcheck
 * initiates `rs.initiate()` but there is a race — Prisma can connect
 * before the replica set election completes. This helper retries a
 * lightweight write until it succeeds or the timeout is exceeded.
 */
async function waitForReplicaSet(prisma: PrismaClient, maxWaitMs = 30_000): Promise<void> {
  const start = Date.now();
  const retryIntervalMs = 1_000;

  while (Date.now() - start < maxWaitMs) {
    try {
      // A simple findMany doesn't require transactions; use deleteMany on a
      // likely-empty collection to exercise the write path that needs the RS.
      await prisma.verificationToken.deleteMany({ where: { identifier: '__rs_probe__' } });
      return;
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : String(error);
      const isReplicaSetNotReady =
        message.includes('Transactions are not supported') ||
        message.includes('not primary') ||
        message.includes('node is recovering');

      if (!isReplicaSetNotReady) {
        throw error; // unexpected error — don't swallow it
      }

      console.info(
        `Waiting for MongoDB replica set to be ready... (${Math.round((Date.now() - start) / 1000)}s)`
      );
      await new Promise((resolve) => setTimeout(resolve, retryIntervalMs));
    }
  }

  throw new Error(
    `MongoDB replica set was not ready after ${maxWaitMs / 1000}s. ` +
      'Ensure the Docker container is running: pnpm run e2e:docker:up'
  );
}

/**
 * Idempotent seed script for the E2E test database. Clears all collections
 * and creates deterministic test data.
 */
async function seedTestDatabase() {
  const allowNonLocal = process.env.E2E_SEED_ALLOW_NONLOCAL === 'true';

  // Safety guard: by default refuse to run against anything except a local test database
  if (!allowNonLocal) {
    let url: URL;

    try {
      url = new URL(E2E_DATABASE_URL);
    } catch {
      throw new Error(
        `E2E seed script could not parse E2E_DATABASE_URL: ${E2E_DATABASE_URL}\n` +
          'Set E2E_DATABASE_URL to a valid local MongoDB URL (e.g. mongodb://localhost:27018/boudreaux-e2e), ' +
          'or set E2E_SEED_ALLOW_NONLOCAL=true to override (DANGEROUS).'
      );
    }

    const isLocalHost = url.hostname === 'localhost' || url.hostname === '127.0.0.1';
    const isExpectedPort = url.port === '27018';
    const isExpectedProtocol = url.protocol === 'mongodb:';

    if (!isLocalHost || !isExpectedPort || !isExpectedProtocol) {
      throw new Error(
        `E2E seed script refusing to run against a non-local or unexpected database: ${E2E_DATABASE_URL}\n` +
          'Set E2E_DATABASE_URL to a local MongoDB instance on mongodb://localhost:27018/boudreaux-e2e, ' +
          'or set E2E_SEED_ALLOW_NONLOCAL=true to override (DANGEROUS).'
      );
    }
  }

  const prisma = new PrismaClient({
    datasourceUrl: E2E_DATABASE_URL,
  });

  try {
    // Wait for the replica set to be ready before proceeding
    await waitForReplicaSet(prisma);

    // Clear all collections in dependency-safe order
    await prisma.releaseDigitalFormatFile.deleteMany({});
    await prisma.releaseDigitalFormat.deleteMany({});
    await prisma.downloadEvent.deleteMany({});
    await prisma.releasePurchase.deleteMany({});
    await prisma.releaseDownload.deleteMany({});
    await prisma.userDownloadQuota.deleteMany({});
    await prisma.tourDateImage.deleteMany({});
    await prisma.tourDateHeadliner.deleteMany({});
    await prisma.tourImage.deleteMany({});
    await prisma.tourDate.deleteMany({});
    await prisma.tour.deleteMany({});
    await prisma.venue.deleteMany({});
    await prisma.artistFeaturedArtist.deleteMany({});
    await prisma.artistRelease.deleteMany({});
    await prisma.artistLabel.deleteMany({});
    await prisma.artistUrl.deleteMany({});
    await prisma.releaseUrl.deleteMany({});
    await prisma.bannerNotification.deleteMany({});
    await prisma.image.deleteMany({});
    await prisma.url.deleteMany({});
    await prisma.featuredArtist.deleteMany({});
    await prisma.release.deleteMany({});
    await prisma.artist.deleteMany({});
    await prisma.authenticator.deleteMany({});
    await prisma.session.deleteMany({});
    await prisma.account.deleteMany({});
    await prisma.verificationToken.deleteMany({});
    await prisma.user.deleteMany({});

    // Create test users
    const adminUser = await prisma.user.create({
      data: {
        id: TEST_USERS.admin.id,
        email: TEST_USERS.admin.email,
        name: TEST_USERS.admin.name,
        username: TEST_USERS.admin.username,
        role: TEST_USERS.admin.role,
        firstName: TEST_USERS.admin.firstName,
        lastName: TEST_USERS.admin.lastName,
        emailVerified: new Date(),
        termsAndConditions: true,
      },
    });

    await prisma.user.create({
      data: {
        id: TEST_USERS.regular.id,
        email: TEST_USERS.regular.email,
        name: TEST_USERS.regular.name,
        username: TEST_USERS.regular.username,
        role: TEST_USERS.regular.role,
        firstName: TEST_USERS.regular.firstName,
        lastName: TEST_USERS.regular.lastName,
        emailVerified: new Date(),
        termsAndConditions: true,
      },
    });

    // Create artists for multi-select testing
    await Promise.all([
      prisma.artist.create({
        data: {
          firstName: 'Test',
          surname: 'Artist One',
          slug: 'test-artist-one',
          displayName: 'Test Artist One',
          publishedOn: new Date(),
        },
      }),
      prisma.artist.create({
        data: {
          firstName: 'Test',
          surname: 'Artist Two',
          slug: 'test-artist-two',
          displayName: 'Test Artist Two',
          publishedOn: new Date(),
        },
      }),
      prisma.artist.create({
        data: {
          firstName: 'Test',
          surname: 'Artist Three',
          slug: 'test-artist-three',
          displayName: 'Test Artist Three',
          publishedOn: new Date(),
        },
      }),
    ]);

    // Create releases for multi-select testing
    await Promise.all([
      prisma.release.create({
        data: {
          title: 'Test Release Alpha',
          releasedOn: new Date('2024-01-15'),
          coverArt: 'https://picsum.photos/seed/release1/400/400',
        },
      }),
      prisma.release.create({
        data: {
          title: 'Test Release Beta',
          releasedOn: new Date('2024-06-15'),
          coverArt: 'https://picsum.photos/seed/release2/400/400',
        },
      }),
    ]);

    // Create notification banners for carousel testing
    const now = new Date();
    const thirtyDaysLater = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    // Create an artist with published releases and tracks for artist page e2e tests
    const e2eArtist = await prisma.artist.create({
      data: {
        firstName: 'E2E',
        surname: 'Artist',
        slug: 'e2e-artist',
        displayName: 'E2E Artist',
        publishedOn: new Date(),
      },
    });

    const e2eRelease1 = await prisma.release.create({
      data: {
        title: 'E2E Album One',
        releasedOn: new Date('2024-03-01'),
        coverArt: 'https://picsum.photos/seed/e2e-release1/400/400',
        publishedAt: new Date(),
        suggestedPrice: 799,
      },
    });

    const e2eRelease2 = await prisma.release.create({
      data: {
        title: 'E2E Album Two',
        releasedOn: new Date('2024-06-01'),
        coverArt: 'https://picsum.photos/seed/e2e-release2/400/400',
        publishedAt: new Date(),
      },
    });

    const e2eRelease3 = await prisma.release.create({
      data: {
        title: 'E2E Album Three',
        releasedOn: new Date('2024-09-01'),
        coverArt: 'https://picsum.photos/seed/e2e-release3/400/400',
        publishedAt: new Date(),
      },
    });

    // Link artist to releases
    await Promise.all([
      prisma.artistRelease.create({
        data: { artistId: e2eArtist.id, releaseId: e2eRelease1.id },
      }),
      prisma.artistRelease.create({
        data: { artistId: e2eArtist.id, releaseId: e2eRelease2.id },
      }),
      prisma.artistRelease.create({
        data: { artistId: e2eArtist.id, releaseId: e2eRelease3.id },
      }),
    ]);

    // Create MP3_320KBPS digital formats with track files for each E2E release.
    // The artist page filters releases to only those with playable MP3_320KBPS files.
    const e2eReleases = [
      { release: e2eRelease1, trackTitle: 'E2E Track Alpha' },
      { release: e2eRelease2, trackTitle: 'E2E Track Beta' },
      { release: e2eRelease3, trackTitle: 'E2E Track Gamma' },
    ];

    for (const { release, trackTitle } of e2eReleases) {
      const format = await prisma.releaseDigitalFormat.create({
        data: {
          releaseId: release.id,
          formatType: 'MP3_320KBPS',
          trackCount: 1,
          totalFileSize: BigInt(5_000_000),
          deletedAt: null,
        },
      });

      await prisma.releaseDigitalFormatFile.create({
        data: {
          formatId: format.id,
          trackNumber: 1,
          title: trackTitle,
          duration: 210,
          s3Key: `releases/${release.id}/audio/mp3_320kbps/01-track.mp3`,
          fileName: '01-track.mp3',
          fileSize: BigInt(5_000_000),
          mimeType: 'audio/mpeg',
        },
      });
    }

    // Add FLAC and WAV formats to E2E Album One for download/purchase flow testing
    const flacFormat = await prisma.releaseDigitalFormat.create({
      data: {
        releaseId: e2eRelease1.id,
        formatType: 'FLAC',
        trackCount: 1,
        totalFileSize: BigInt(30_000_000),
        deletedAt: null,
      },
    });

    await prisma.releaseDigitalFormatFile.create({
      data: {
        formatId: flacFormat.id,
        trackNumber: 1,
        title: 'E2E Track Alpha',
        duration: 210,
        s3Key: `releases/${e2eRelease1.id}/audio/flac/01-track.flac`,
        fileName: '01-track.flac',
        fileSize: BigInt(30_000_000),
        mimeType: 'audio/flac',
      },
    });

    const wavFormat = await prisma.releaseDigitalFormat.create({
      data: {
        releaseId: e2eRelease1.id,
        formatType: 'WAV',
        trackCount: 1,
        totalFileSize: BigInt(50_000_000),
        deletedAt: null,
      },
    });

    await prisma.releaseDigitalFormatFile.create({
      data: {
        formatId: wavFormat.id,
        trackNumber: 1,
        title: 'E2E Track Alpha',
        duration: 210,
        s3Key: `releases/${e2eRelease1.id}/audio/wav/01-track.wav`,
        fileName: '01-track.wav',
        fileSize: BigInt(50_000_000),
        mimeType: 'audio/wav',
      },
    });

    // Create a purchase record for regular user on E2E Album One (for download tests)
    await prisma.releasePurchase.create({
      data: {
        userId: TEST_USERS.regular.id,
        releaseId: e2eRelease1.id,
        amountPaid: 799,
        stripePaymentIntentId: 'pi_e2e_test_purchase_album_one',
        stripeSessionId: 'cs_e2e_test_session_album_one',
        purchasedAt: new Date(),
      },
    });

    await Promise.all([
      prisma.bannerNotification.create({
        data: {
          slotNumber: 1,
          content: 'E2E Test Banner One — First test notification',
          textColor: '#ffffff',
          backgroundColor: '#16213e',
          displayFrom: now,
          displayUntil: thirtyDaysLater,
          addedBy: { connect: { id: adminUser.id } },
        },
      }),
      prisma.bannerNotification.create({
        data: {
          slotNumber: 2,
          content: 'E2E Test Banner Two — Second test notification',
          textColor: '#ffffff',
          backgroundColor: '#533483',
          displayFrom: now,
          displayUntil: thirtyDaysLater,
          addedBy: { connect: { id: adminUser.id } },
        },
      }),
      prisma.bannerNotification.create({
        data: {
          slotNumber: 3,
          content: 'E2E Test Banner Three — Third test notification',
          textColor: '#ffffff',
          backgroundColor: '#e94560',
          displayFrom: now,
          displayUntil: thirtyDaysLater,
          addedBy: { connect: { id: adminUser.id } },
        },
      }),
    ]);

    console.info('E2E test database seeded successfully.');
  } finally {
    await prisma.$disconnect();
  }
}

export { seedTestDatabase, TEST_USERS };
